# Generated by Django 4.2.29 on 2026-03-12 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bolna_call_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Call ID returned by Bolna API",
                        max_length=255,
                    ),
                ),
                (
                    "agent_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Agent configuration sent to Bolna for this call",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("calling", "Calling"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Call duration in seconds"
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True, help_text="S3/MinIO URL to the call recording"
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Full transcript of the call"
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI-generated candidate score (0-100)",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the call"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of retry attempts made"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if the call failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "candidate_calls",
                "ordering": ["-created_at"],
            },
        ),
    ]
