# Generated by Django 4.2.29 on 2026-03-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatecall",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="candidates.candidate",
            ),
        ),
        migrations.AddIndex(
            model_name="candidatecall",
            index=models.Index(
                fields=["candidate", "status"], name="candidate_c_candida_d08a25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatecall",
            index=models.Index(
                fields=["bolna_call_id"], name="candidate_c_bolna_c_2e490d_idx"
            ),
        ),
    ]
