# Generated by Django 4.2.29 on 2026-03-12 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "resume_url",
                    models.URLField(
                        blank=True, help_text="S3/MinIO URL to the uploaded resume"
                    ),
                ),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of skill strings, e.g. ["Python", "Django"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("screening", "Screening"),
                            ("interviewed", "Interviewed"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "candidates",
                "ordering": ["-created_at"],
            },
        ),
    ]
