# Generated by Django 4.2.29 on 2026-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("screening", "Screening"),
                    ("qualified", "Qualified"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                db_index=True,
                default="new",
                max_length=15,
            ),
        ),
    ]
