# Generated by Django 4.2.29 on 2026-03-12 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0003_alter_candidate_status"),
        ("jobs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("hr", "HR"),
                            ("managerial", "Managerial"),
                            ("final", "Final"),
                        ],
                        default="technical",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Interviewer rating 1-10", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "status"],
                        name="interviews_candida_2622d8_idx",
                    )
                ],
            },
        ),
    ]
